openapi: 3.0.0
servers:
    -   url: '{protocol}://{api_host}/store-api/v1'
        variables:
            protocol:
                default: 'https'
                description: transfer protocol (HTTP or HTTPS)
            api_host:
                default: 'shopware-platform.test'
                description: 'Host of your Shopware 6 instance'
info:
    title: Shopware Sales-Channel-API Extension
    version: 0.1.2
paths:
    '/pwa/page':
        post:
            summary: Resolve page content for a given path.
            operationId: pwa.page
            parameters:
                - in: query
                  name: limit
                  schema:
                      type: integer
                      default: 25
                - in: query
                  name: page
                  schema:
                      type: integer
                      default: 1
                - in: query
                  name: sorting
                  schema:
                      type: string
                      default: 'name-asc'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                path:
                                    type: string
                                    default: '/my-page/needs-a-resolve'
                                    description: 'Path identifying the page to be resolved'
            responses:
                '200':
                    description: Resolved and hydrated page
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: '#/components/schemas/navigation_page_response'
                                    - $ref: '#/components/schemas/product_page_response'
    '/pwa/navigation':
        post:
            summary: Get navigation tree for a given root node
            operationId: pwa.navigation
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                depth:
                                    type: integer
                                    description: 'Depth of the tree (1 = only  fetch first level children; -1 = fetch full tree)'
                                rootNode:
                                    type: string
                                    format: uuid
                                    description: 'Relative root for the tree to be fetched from'
            responses:
                '200':
                    description: Resolved navigation tree
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    count:
                                        type: integer
                                    elements:
                                        type: array
                                        items:
                                            $ref: '#/components/schemas/navigation_tree_item'

components:
    schemas:

        navigation_tree_item:
            type: object
            properties:
                route:
                    type: object
                    properties:
                        path:
                            type: string
                        resourceType:
                            type: string
                name:
                    type: string
                children:
                    type: array
                    items:
                        $ref: '#/components/schemas/navigation_tree_item'
                count:
                    type: integer
                level:
                    type: integer
        route_flat:
            type: object
            properties:
                routeName:
                    type: string
                pathInfo:
                    type: string
                seoPathInfo:
                    type: string
                isCanonical:
                    type: boolean
                resource:
                    type: string
                resourceIdentifier:
                    type: string
                    format: uuid
                extensions:
                    type: array
                    items:
                        type: object
        criteria:
            type: object
            properties:
                page:
                    type: integer
                limit:
                    type: integer
                sort:
                    type: string
                filter:
                    type: array
                    items:
                        $ref: '#/components/schemas/filter'
        filter:
            type: object
            properties:
                type:
                    type: string
                field:
                    type: string
                value:
                    type: string

        navigation_page_response:
            type: object
            properties:
                resourceType:
                    type: string
                resourceId:
                    type: string
                    format: uuid
                cmsPage:
                    $ref: '#/components/schemas/cms_page'
                breadcrumb:
                    type: object
        product_page_response:
            type: object
            properties:
                resourceType:
                    type: string
                resourceId:
                    type: string
                    format: uuid
                product:
                    type: string

        cms_page:
            type: object
            properties:
                name:
                    type: string
                type:
                    type: string
                entity:
                    type: string
                sections:
                    type: array
                    items:
                        $ref: '#/components/schemas/cms_section'

        cms_section:
            type: object
            properties:
                type:
                    type: string
                blocks:
                    type: array
                    items:
                        $ref: '#/components/schemas/cms_block'
        cms_block:
            type: object
            properties:
                type:
                    type: string
                slots:
                    type: array
                    items:
                        $ref: '#/components/schemas/cms_slot'

        cms_slot:
            type: object
            properties:
                type:
                    type: string
                slot:
                    type: string
                block:
                    type: string
                blockId:
                    type: string
                    format: uuid
                config:
                    type: object
                fieldConfig:
                    type: array
                    description: "Configuration overrides"
                    items:
                        $ref: '#/components/schemas/cms_field_config'

        cms_field_config:
            type: object
            properties:
                name:
                    type: string
                source:
                    type: string
                value:
                    type: string

    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: sw-access-key
security:
    - ApiKey: []
